# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JMS\Documents\msite\MSite\UI\msite4Acquisition.ui'
#
# Created: Thu Oct 22 17:22:11 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from common.dialogs.mplwidget import MplWidgetSEM
from msite4A.mtableWidget import TableWidgetDragRows
import common.dialogs.resources_rc

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MSiteAcq(QMainWindow):
    def setupUi(self, MSiteAcq):
        MSiteAcq.setObjectName(_fromUtf8("MSiteAcq"))
        MSiteAcq.setWindowModality(QtCore.Qt.ApplicationModal)
        screen = QDesktopWidget().screenGeometry()
        px = int(screen.width()*(1450.0/1920))
        py = int(screen.height()*(825.0/1080))
        MSiteAcq.resize(px, py)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MSiteAcq.sizePolicy().hasHeightForWidth())
        MSiteAcq.setSizePolicy(sizePolicy)
#        MSiteAcq.setStyleSheet(_fromUtf8("border-color:rgb(0,250, 0);\n"
#        "color: rgb(0,121, 64);"))
        palette = QPalette()
        brush_green = QBrush(QColor(0, 121, 64))
        brush_green.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush_green)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush_green)
        brush = QBrush(QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush_green)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush_green)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush_green)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush_green)
        MSiteAcq.setPalette(palette)
        icon = QIcon()
        icon.addPixmap(QPixmap(_fromUtf8(":/res/msite2.png")), QIcon.Normal, QIcon.Off)
        MSiteAcq.setWindowIcon(icon)

        MSiteAcq.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MSiteAcq.setDocumentMode(False)
        MSiteAcq.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MSiteAcq)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (400.0 / 1080))
        pxe = int(screen.width() * (411.0 / 1920))
        pye = int(screen.height() * (301.0 / 1080))
        self.groupBox_5.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.groupBox_5.setPalette(palette)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.textBrowserMessages = QTextBrowser(self.groupBox_5)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (381.0 / 1920))
        pye = int(screen.height() * (261.0 / 1080))
        self.textBrowserMessages.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.textBrowserMessages.setPalette(palette)
        self.textBrowserMessages.setObjectName(_fromUtf8("textBrowserMessages"))
        self.gridView = MplWidgetSEM(self.centralwidget)
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (401.0 / 1920))
        pye = int(screen.height() * (361.0 / 1080))
        self.gridView.setGeometry(QtCore.QRect(px, py, pxe, pye))
       
        self.gridView.setPalette(palette)
        self.gridView.setAutoFillBackground(False)
        self.gridView.setStyleSheet(_fromUtf8("background-color: black;"))
        self.gridView.setObjectName(_fromUtf8("gridView"))
        self.toolBox = QToolBox(self.centralwidget)
        px = int(screen.width() * (460.0 / 1920))
        py = int(screen.height() * (10.0 / 1080))
        pxe = int(screen.width() * (961.0 / 1920))
        pye = int(screen.height() * (711.0 / 1080))
        self.toolBox.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.toolBox.setPalette(palette)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setFrameShape(QFrame.WinPanel)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_general = QWidget()
        pxe = int(screen.width() * (957.0 / 1920))
        pye = int(screen.height() * (653.0 / 1080))
        self.page_general.setGeometry(QtCore.QRect(0, 0, pxe, pye))
        self.page_general.setObjectName(_fromUtf8("page_general"))
        self.groupBoxServer = QGroupBox(self.page_general)
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (10.0 / 1080))
        pxe = int(screen.width() * (401.0 / 1920))
        pye = int(screen.height() * (161.0 / 1080))
        self.groupBoxServer.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.groupBoxServer.setPalette(palette)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxServer.setFont(font)
        self.groupBoxServer.setObjectName(_fromUtf8("groupBoxServer"))
        self.hostLineEdit = QLineEdit(self.groupBoxServer)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (40.0 / 1080))
        pxe = int(screen.width() * (109.0 / 1920))
        pye = int(screen.height() * (20.0 / 1080))
        self.hostLineEdit.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.hostLineEdit.setPalette(palette)
        self.hostLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.hostLineEdit.setObjectName(_fromUtf8("hostLineEdit"))
        self.portLineEdit = QLineEdit(self.groupBoxServer)
        px = int(screen.width() * (120.0 / 1920))
        py = int(screen.height() * (40.0 / 1080))
        pxe = int(screen.width() * (61.0 / 1920))
        pye = int(screen.height() * (20.0 / 1080))
        self.portLineEdit.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.portLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.portLineEdit.setObjectName(_fromUtf8("portLineEdit"))
        self.layoutWidget_8 = QWidget(self.groupBoxServer)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (80.0 / 1080))
        pxe = int(screen.width() * (327.0 / 1920))
        pye = int(screen.height() * (48.0 / 1080))
        self.layoutWidget_8.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_10 = QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_10.setContentsMargins(0,0,0,0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_Connect = QPushButton(self.layoutWidget_8)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Connect.setFont(font)
        self.pushButton_Connect.setDefault(False)
        self.pushButton_Connect.setFlat(False)
        self.pushButton_Connect.setObjectName(_fromUtf8("pushButton_Connect"))
        self.horizontalLayout_10.addWidget(self.pushButton_Connect)
        self.pushButton_Refresh = QPushButton(self.layoutWidget_8)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Refresh.setFont(font)
        self.pushButton_Refresh.setObjectName(_fromUtf8("pushButton_Refresh"))
        self.horizontalLayout_10.addWidget(self.pushButton_Refresh)
        self.layoutWidget_9 = QWidget(self.groupBoxServer)
        px = int(screen.width() * (190.0 / 1920))
        py = int(screen.height() * (40.0 / 1080))
        pxe = int(screen.width() * (200.0 / 1920))
        pye = int(screen.height() * (29.0 / 1080))
        self.layoutWidget_9.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_11 = QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(0,0,0,0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_Connect = QLabel(self.layoutWidget_9)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_Connect.setFont(font)
        self.label_Connect.setObjectName(_fromUtf8("label_Connect"))
        self.horizontalLayout_11.addWidget(self.label_Connect)
        self.label_Led = QLabel(self.layoutWidget_9)
        self.label_Led.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Led.setText(_fromUtf8(""))
        self.label_Led.setPixmap(QPixmap(_fromUtf8(":/res/LedNone.ico")))
        self.label_Led.setScaledContents(False)
        self.label_Led.setObjectName(_fromUtf8("label_Led"))
        self.horizontalLayout_11.addWidget(self.label_Led)
        self.groupBox_2 = QGroupBox(self.page_general)
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (180.0 / 1080))
        pxe = int(screen.width() * (921.0 / 1920))
        pye = int(screen.height() * (371.0 / 1080))
        self.groupBox_2.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_6 = QWidget(self.groupBox_2)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (309.0 / 1920))
        pye = int(screen.height() * (41.0 / 1080))
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0,0,0,0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QLabel(self.horizontalLayoutWidget_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.horizontalLayoutWidget_7 = QWidget(self.groupBox_2)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (80.0 / 1080))
        pxe = int(screen.width() * (309.0 / 1920))
        pye = int(screen.height() * (41.0 / 1080))
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_9 = QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0,0,0,0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_12 = QLabel(self.horizontalLayoutWidget_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.comboBox_Setup = QComboBox(self.horizontalLayoutWidget_7)
        self.comboBox_Setup.setObjectName(_fromUtf8("comboBox_Setup"))
        self.comboBox_Setup.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBox_Setup)
        self.pushButton_newSetup = QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_newSetup.setMaximumWidth(40)
        self.pushButton_newSetup.setObjectName(_fromUtf8("pushButton_newSetup"))
        self.horizontalLayout_9.addWidget(self.pushButton_newSetup)
        self.groupBox_3 = QGroupBox(self.groupBox_2)
        px = int(screen.width() * (350.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (551.0 / 1920))
        pye = int(screen.height() * (163.0 / 1080))
        self.groupBox_3.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_generalName = QLabel(self.groupBox_3)
        self.label_generalName.setObjectName(_fromUtf8("label_generalName"))
        self.horizontalLayout_13.addWidget(self.label_generalName)
        self.lineEdit_generalName = QLineEdit(self.groupBox_3)
        self.lineEdit_generalName.setObjectName(_fromUtf8("lineEdit_generalName"))
        self.horizontalLayout_13.addWidget(self.lineEdit_generalName)
        self.checkBox = QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_13.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 0, 1, 2)
        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_startswith = QLabel(self.groupBox_3)
        self.label_startswith.setObjectName(_fromUtf8("label_startswith"))
        self.horizontalLayout_14.addWidget(self.label_startswith)
        self.spinBox_swnumber = QSpinBox(self.groupBox_3)
        
        self.spinBox_swnumber.setObjectName(_fromUtf8("spinBox_swnumber"))
        self.horizontalLayout_14.addWidget(self.spinBox_swnumber)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 4, 0, 1, 1)
        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_endswith = QLabel(self.groupBox_3)
        self.label_endswith.setObjectName(_fromUtf8("label_endswith"))
        self.horizontalLayout_15.addWidget(self.label_endswith)
        self.lineEdit_endsWith = QLineEdit(self.groupBox_3)
       
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        self.lineEdit_endsWith.setPalette(palette)
        self.lineEdit_endsWith.setText(_fromUtf8(""))
        self.lineEdit_endsWith.setObjectName(_fromUtf8("lineEdit_endsWith"))
        self.horizontalLayout_15.addWidget(self.lineEdit_endsWith)
        self.checkBox_date = QCheckBox(self.groupBox_3)
        self.checkBox_date.setObjectName(_fromUtf8("checkBox_date"))
        self.horizontalLayout_15.addWidget(self.checkBox_date)
        self.comboBox_dateFormat = QComboBox(self.groupBox_3)
        self.comboBox_dateFormat.setObjectName(_fromUtf8("comboBox_dateFormat"))
        self.comboBox_dateFormat.addItem(_fromUtf8(""))
        self.comboBox_dateFormat.addItem(_fromUtf8(""))
        self.comboBox_dateFormat.addItem(_fromUtf8(""))
        self.comboBox_dateFormat.setItemText(2, _fromUtf8(""))
        self.horizontalLayout_15.addWidget(self.comboBox_dateFormat)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 3, 0, 1, 1)
        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_ProjectName = QLabel(self.groupBox_3)
        self.label_ProjectName.setObjectName(_fromUtf8("label_ProjectName"))
        self.horizontalLayout_16.addWidget(self.label_ProjectName)
        self.lineEdit_projectName = QLineEdit(self.groupBox_3)
        
        self.lineEdit_projectName.setPalette(palette)
        self.lineEdit_projectName.setObjectName(_fromUtf8("lineEdit_projectName"))
        self.horizontalLayout_16.addWidget(self.lineEdit_projectName)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 0, 0, 1, 2)
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (190.0 / 1080))
        pxe = int(screen.width() * (881.0 / 1920))
        pye = int(screen.height() * (161.0 / 1080))
        self.groupBox_4.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayoutWidget_8 = QWidget(self.groupBox_4)
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (309.0 / 1920))
        pye = int(screen.height() * (41.0 / 1080))
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_12 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_12.setContentsMargins(0,0,0,0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_15 = QLabel(self.horizontalLayoutWidget_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_12.addWidget(self.label_15)
        self.comboBox_ROI = QComboBox(self.horizontalLayoutWidget_8)
        self.comboBox_ROI.setObjectName(_fromUtf8("comboBox_ROI"))
        self.comboBox_ROI.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_ROI)
        self.pushButton_newROI = QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_newROI.setMaximumWidth(40)
        self.pushButton_newROI.setObjectName(_fromUtf8("pushButton_newROI"))
        self.horizontalLayout_12.addWidget(self.pushButton_newROI)
        self.layoutWidget = QWidget(self.groupBox_4)
        px = int(screen.width() * (350.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (381.0 / 1920))
        pye = int(screen.height() * (80.0 / 1080))
        self.layoutWidget.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_lx = QLabel(self.layoutWidget)
        self.label_lx.setObjectName(_fromUtf8("label_lx"))
        self.horizontalLayout_17.addWidget(self.label_lx)
        self.doubleSpinBox = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_17.addWidget(self.doubleSpinBox)
        self.label_umx = QLabel(self.layoutWidget)
        self.label_umx.setObjectName(_fromUtf8("label_umx"))
        self.horizontalLayout_17.addWidget(self.label_umx)
        self.gridLayout.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_16 = QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_18.addWidget(self.label_16)
        self.doubleSpinBox_ly = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_ly.setMaximum(10000.0)
        self.doubleSpinBox_ly.setMinimum(0.0)
        self.doubleSpinBox_ly.setObjectName(_fromUtf8("doubleSpinBox_ly"))
        self.horizontalLayout_18.addWidget(self.doubleSpinBox_ly)
        self.label_18 = QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_18.addWidget(self.label_18)
        self.gridLayout.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_19 = QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_depth = QLabel(self.layoutWidget)
        self.label_depth.setObjectName(_fromUtf8("label_depth"))
        self.horizontalLayout_19.addWidget(self.label_depth)
        self.doubleSpinBox_depth = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_depth.setMaximum(10000.0)
        self.doubleSpinBox_depth.setObjectName(_fromUtf8("doubleSpinBox_depth"))
        self.horizontalLayout_19.addWidget(self.doubleSpinBox_depth)
        self.label_19 = QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_19.addWidget(self.label_19)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.pushButton_save = QPushButton(self.page_general)
        px = int(screen.width() * (850.0 / 1920))
        py = int(screen.height() * (560.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (51.0 / 1080))
        self.pushButton_save.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.toolBox.addItem(self.page_general, _fromUtf8(""))
        self.page_list = QWidget()
        self.page_list.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_list.setObjectName(_fromUtf8("page_list"))
        self.groupBox_MainControls = QGroupBox(self.page_list)

        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (10.0 / 1080))
        pxe = int(screen.width() * (521.0 / 1920))
        pye = int(screen.height() * (101.0 / 1080))
        self.groupBox_MainControls.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_MainControls.setFont(font)
        self.groupBox_MainControls.setObjectName(_fromUtf8("groupBox_MainControls"))
        self.pushButton_Pause = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (80.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Pause.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Pause.setText(_fromUtf8(""))
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(_fromUtf8(":/res/pause.ico")), QIcon.Normal, QIcon.Off)
        self.pushButton_Pause.setIcon(icon1)
        self.pushButton_Pause.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Pause.setObjectName(_fromUtf8("pushButton_Pause"))
        self.pushButton_Start = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Start.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Start.setText(_fromUtf8(""))
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(_fromUtf8(":/res/play.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Start.setIcon(icon2)
        self.pushButton_Start.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.pushButton_Resume = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (150.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Resume.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Resume.setText(_fromUtf8(""))
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(_fromUtf8(":/res/resume.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Resume.setIcon(icon3)
        self.pushButton_Resume.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Resume.setObjectName(_fromUtf8("pushButton_Resume"))
        self.pushButton_Features = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (350.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Features.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Features.setText(_fromUtf8(""))
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(_fromUtf8(":/res/shapes.ico")), QIcon.Normal, QIcon.Off)
        self.pushButton_Features.setIcon(icon4)
        self.pushButton_Features.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Features.setObjectName(_fromUtf8("pushButton_Features"))
        self.pushButton_Skip = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (280.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Skip.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Skip.setText(_fromUtf8(""))
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(_fromUtf8(":/res/next.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Skip.setIcon(icon5)
        self.pushButton_Skip.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_Skip.setObjectName(_fromUtf8("pushButton_Skip"))
        self.pushButton_Stop = QPushButton(self.groupBox_MainControls)
        px = int(screen.width() * (430.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (71.0 / 1920))
        pye = int(screen.height() * (61.0 / 1080))
        self.pushButton_Stop.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.pushButton_Stop.setText(_fromUtf8(""))
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(_fromUtf8(":/res/stop.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Stop.setIcon(icon6)
        self.pushButton_Stop.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.groupBox_PointsList = QGroupBox(self.page_list)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (120.0 / 1080))
        pxe = int(screen.width() * (931.0 / 1920))
        pye = int(screen.height() * (521.0 / 1080))
        self.groupBox_PointsList.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_PointsList.setFont(font)
        self.groupBox_PointsList.setObjectName(_fromUtf8("groupBox_PointsList"))
        self.tableTasks = TableWidgetDragRows(self.groupBox_PointsList)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (911.0 / 1920))
        pye = int(screen.height() * (451.0 / 1080))
        self.tableTasks.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.tableTasks.setMinimumSize(QtCore.QSize(861, 431))
        self.tableTasks.setAutoFillBackground(False)
        self.tableTasks.setStyleSheet(_fromUtf8("background-color: rgb(242, 255, 255);"))
        self.tableTasks.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableTasks.setAlternatingRowColors(True)
        self.tableTasks.setRowCount(2)
        self.tableTasks.setColumnCount(10)
        self.tableTasks.setObjectName(_fromUtf8("tableTasks"))
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.tableTasks.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.tableTasks.setItem(0, 1, item)
        self.tableTasks.horizontalHeader().setCascadingSectionResizes(False)
        self.pushButton_save_changes = QPushButton(self.groupBox_PointsList)
        self.pushButton_save_changes.setObjectName(_fromUtf8("pushButton_save_changes"))
        px = int(screen.width() * (20.0 / 1920))
        py = int(screen.height() * (480.0 / 1080))
        pxe = int(screen.width() * (141.0 / 1920))
        pye = int(screen.height() * (31.0 / 1080))
        self.pushButton_save_changes.setGeometry(QtCore.QRect(px, py, pxe, pye))
        ##
        self.pushButton_select_all = QPushButton(self.groupBox_PointsList)
        self.pushButton_select_all.setObjectName(_fromUtf8("pushButton_select_all"))
        px = int(screen.width() * (160.0 / 1920))
        py = int(screen.height() * (480.0 / 1080))
        pxe = int(screen.width() * (141.0 / 1920))
        pye = int(screen.height() * (31.0 / 1080))
        self.pushButton_select_all.setGeometry(QtCore.QRect(px, py, pxe, pye))


        self.pushButton_deselect_all = QPushButton(self.groupBox_PointsList)
        self.pushButton_deselect_all.setObjectName(_fromUtf8("pushButton_deselect_all"))
        px = int(screen.width() * (300.0 / 1920))
        py = int(screen.height() * (480.0 / 1080))
        pxe = int(screen.width() * (141.0 / 1920))
        pye = int(screen.height() * (31.0 / 1080))
        self.pushButton_deselect_all.setGeometry(QtCore.QRect(px, py, pxe, pye))

        self.comboBox_StatusTarget = QComboBox(self.groupBox_PointsList)
        self.comboBox_StatusTarget.setObjectName(_fromUtf8("comboBox_StatusTarget"))
        px = int(screen.width() * (600.0 / 1920))
        py = int(screen.height() * (480.0 / 1080))
        pxe = int(screen.width() * (138.0 / 1920))
        pye = int(screen.height() * (29.0 / 1080))
        self.comboBox_StatusTarget.setGeometry(QtCore.QRect(px, py, pxe, pye))

        ##

        self.groupBox = QGroupBox(self.page_list)
        px = int(screen.width() * (540.0 / 1920))
        py = int(screen.height() * (10.0 / 1080))
        pxe = int(screen.width() * (381.0 / 1920))
        pye = int(screen.height() * (101.0 / 1080))
        self.groupBox.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget1 = QWidget(self.groupBox)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (361.0 / 1920))
        pye = int(screen.height() * (50.0 / 1080))
        self.layoutWidget1.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.progressBarTotal = QProgressBar(self.layoutWidget1)
        self.progressBarTotal.setProperty("value", 0)
        self.progressBarTotal.setObjectName(_fromUtf8("progressBarTotal"))
        self.horizontalLayout.addWidget(self.progressBarTotal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_Status = QLabel(self.layoutWidget1)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Status.setFont(font)
        self.label_Status.setObjectName(_fromUtf8("label_Status"))
        self.verticalLayout.addWidget(self.label_Status)
        self.toolBox.addItem(self.page_list, _fromUtf8(""))
        MSiteAcq.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MSiteAcq)
        px = int(screen.width() * (0.0 / 1920))
        py = int(screen.height() * (0.0 / 1080))
        pxe = int(screen.width() * (1450.0 / 1920))
        pye = int(screen.height() * (21.0 / 1080))
        self.menubar.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Actions = QMenu(self.menubar)
        self.menu_Actions.setObjectName(_fromUtf8("menu_Actions"))
        MSiteAcq.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MSiteAcq)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MSiteAcq.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MSiteAcq)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MSiteAcq.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Load_List = QAction(MSiteAcq)
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(_fromUtf8(":/res/coord_green.png")), QIcon.Normal, QIcon.Off)
        self.action_Load_List.setIcon(icon7)
        self.action_Load_List.setObjectName(_fromUtf8("action_Load_List"))

        self.action_Load_Map = QAction(MSiteAcq)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(_fromUtf8(":/res/map_target.ico")), QIcon.Normal, QIcon.Off)
        self.action_Load_Map.setIcon(icon8)
        self.action_Load_Map.setObjectName(_fromUtf8("action_Load_Map"))

        self.actionUpdateMap= QAction(MSiteAcq)
        self.actionUpdateMap.setObjectName(_fromUtf8("actionUpdateMap"))

        self.action_pushbc = QAction(MSiteAcq)
        self.action_pushbc.setObjectName(_fromUtf8("action_pushbc"))

        self.action_stop_after_finished = QAction(MSiteAcq)
        self.action_stop_after_finished.setObjectName(_fromUtf8("action_stop_after_finished"))
        self.action_stop_after_finished.setCheckable(True)
        self.action_stop_after_finished.setChecked(False)

        self.action_AFASEmergency = QAction(MSiteAcq)
        self.action_AFASEmergency.setObjectName(_fromUtf8("action_AFAS"))
        self.action_SwapCP = QAction(MSiteAcq)
        self.action_SwapCP.setObjectName(_fromUtf8("action_SwapCP"))

        self.actionRun = QAction(MSiteAcq)
        self.actionRun.setIcon(icon2)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionStop = QAction(MSiteAcq)
        icon16 = QIcon()
        icon16.addPixmap(QPixmap(_fromUtf8(":/res/stop.png")), QIcon.Normal, QIcon.Off)
        self.actionStop.setIcon(icon16)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QAction(MSiteAcq)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionResume = QAction(MSiteAcq)
        self.actionResume.setIcon(icon3)
        self.actionResume.setObjectName(_fromUtf8("actionResume"))
        self.actionSave_Project = QAction(MSiteAcq)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(_fromUtf8(":/res/save.ico")), QIcon.Normal, QIcon.Off)
        self.actionSave_Project.setIcon(icon8)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionLoad_Project = QAction(MSiteAcq)
        self.actionLoad_Project.setObjectName(_fromUtf8("actionLoad_Project"))
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Load_List)
        self.menu_File.addAction(self.action_Load_Map)
        self.menu_File.addAction(self.actionSave_Project)
        self.menu_File.addAction(self.actionLoad_Project)
        self.menu_File.addAction(self.actionUpdateMap)
        self.menu_Actions.addSeparator()
        self.menu_Actions.addAction(self.actionRun)
        self.menu_Actions.addAction(self.actionStop)
        self.menu_Actions.addAction(self.actionPause)
        self.menu_Actions.addAction(self.actionResume)
        self.menu_Actions.addAction(self.action_pushbc)
        self.menu_Actions.addAction(self.action_stop_after_finished)
        self.menu_Actions.addAction(self.action_AFASEmergency)
        self.menu_Actions.addAction(self.action_SwapCP)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Actions.menuAction())
        self.toolBar.addAction(self.action_Load_Map)
        self.toolBar.addAction(self.action_Load_List)
        self.toolBar.addAction(self.actionSave_Project)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionResume)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionPause)

        self.retranslateUi(MSiteAcq)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MSiteAcq)
        MSiteAcq.setTabOrder(self.hostLineEdit, self.portLineEdit)
        MSiteAcq.setTabOrder(self.portLineEdit, self.pushButton_Connect)
        MSiteAcq.setTabOrder(self.pushButton_Connect, self.pushButton_Refresh)
        MSiteAcq.setTabOrder(self.pushButton_Refresh, self.pushButton_newSetup)
        MSiteAcq.setTabOrder(self.pushButton_newSetup, self.lineEdit_projectName)
        MSiteAcq.setTabOrder(self.lineEdit_projectName, self.lineEdit_generalName)
        MSiteAcq.setTabOrder(self.lineEdit_generalName, self.checkBox)
        MSiteAcq.setTabOrder(self.checkBox, self.lineEdit_endsWith)
        MSiteAcq.setTabOrder(self.lineEdit_endsWith, self.checkBox_date)
        MSiteAcq.setTabOrder(self.checkBox_date, self.comboBox_dateFormat)
        MSiteAcq.setTabOrder(self.comboBox_dateFormat, self.comboBox_ROI)
        MSiteAcq.setTabOrder(self.comboBox_ROI, self.spinBox_swnumber)
        MSiteAcq.setTabOrder(self.spinBox_swnumber, self.pushButton_newROI)
        MSiteAcq.setTabOrder(self.pushButton_newROI, self.doubleSpinBox)
        MSiteAcq.setTabOrder(self.doubleSpinBox, self.doubleSpinBox_ly)
        MSiteAcq.setTabOrder(self.doubleSpinBox_ly, self.doubleSpinBox_depth)
        MSiteAcq.setTabOrder(self.doubleSpinBox_depth, self.pushButton_save)
        MSiteAcq.setTabOrder(self.pushButton_save, self.gridView)
        MSiteAcq.setTabOrder(self.gridView, self.textBrowserMessages)
        MSiteAcq.setTabOrder(self.textBrowserMessages, self.pushButton_Skip)
        MSiteAcq.setTabOrder(self.pushButton_Skip, self.pushButton_Stop)
        MSiteAcq.setTabOrder(self.pushButton_Stop, self.tableTasks)
        MSiteAcq.setTabOrder(self.tableTasks, self.pushButton_Resume)
        MSiteAcq.setTabOrder(self.pushButton_Resume, self.pushButton_save_changes)
        MSiteAcq.setTabOrder(self.pushButton_save_changes, self.pushButton_Features)
        MSiteAcq.setTabOrder(self.pushButton_Features, self.pushButton_Start)
        MSiteAcq.setTabOrder(self.pushButton_Start, self.pushButton_Pause)

    def retranslateUi(self, MSiteAcq):
        MSiteAcq.setWindowTitle(_translate("MSiteAcq", "MSite4 Acquisition Client", None))
        self.groupBox_5.setTitle(_translate("MSiteAcq", "Messages", None))
        self.gridView.setToolTip(_translate("MSiteAcq", "<html><head/><body><p align=\"justify\">In this grid, you can look at your sample positions. </p><p align=\"justify\">Load your points coming from your Light Microscopy.</p></body></html>", None))
        self.groupBoxServer.setTitle(_translate("MSiteAcq", "msite4ATLAS Server", None))
        self.hostLineEdit.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Ip address of SEM Server</p></body></html>", None))
        self.hostLineEdit.setInputMask(_translate("MSiteAcq", "000.000.000.000; ", None))
        self.portLineEdit.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Port of your server</p></body></html>", None))
        self.portLineEdit.setInputMask(_translate("MSiteAcq", "00000; ", None))
        self.pushButton_Connect.setText(_translate("MSiteAcq", "Connect", None))
        self.pushButton_Refresh.setText(_translate("MSiteAcq", "Save state", None))
        self.label_Connect.setText(_translate("MSiteAcq", "Not connected       ", None))
        self.label_12.setText(_translate("MSiteAcq", "Setup:", None))
        self.pushButton_newSetup.setText(_translate("MSiteAcq", "+", None))
        self.groupBox_3.setTitle(_translate("MSiteAcq", "Sample Folder Naming", None))
        self.label_generalName.setText(_translate("MSiteAcq", "Sample general name :", None))
        self.checkBox.setText(_translate("MSiteAcq", "Use same names as coordinates file", None))
        self.label_startswith.setText(_translate("MSiteAcq", "Numbering starts with: ", None))
        self.label_endswith.setText(_translate("MSiteAcq", "Ends with :", None))
        self.checkBox_date.setText(_translate("MSiteAcq", "Date", None))
        self.comboBox_dateFormat.setItemText(0, _translate("MSiteAcq", "hhmm_ddMMyyyy", None))
        self.comboBox_dateFormat.setItemText(1, _translate("MSiteAcq", "yyyyMMdd_hhmm", None))
        self.label_ProjectName.setText(_translate("MSiteAcq", "Project title :", None))
        self.groupBox_4.setTitle(_translate("MSiteAcq", "ROI Imaging Volume", None))
        self.label_15.setText(_translate("MSiteAcq", "Imaging ROI :", None))
        self.pushButton_newROI.setText(_translate("MSiteAcq", "+", None))
        self.label_lx.setText(_translate("MSiteAcq", "Width :", None))
        self.label_umx.setText(_translate("MSiteAcq", "μm", None))
        self.label_16.setText(_translate("MSiteAcq", "Height:", None))
        self.label_18.setText(_translate("MSiteAcq", "μm", None))
        self.label_depth.setText(_translate("MSiteAcq", "Depth (same as in recipe):      ", None))
        self.label_19.setText(_translate("MSiteAcq", "μm", None))
        self.pushButton_save.setText(_translate("MSiteAcq", "Save", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_general), _translate("MSiteAcq", "General Settings", None))
        self.groupBox_MainControls.setTitle(_translate("MSiteAcq", "Main Controls", None))
        self.pushButton_Pause.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Pause imaging (milling continues)</p></body></html>", None))
        self.pushButton_Start.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Start - all samples.</p></body></html>", None))
        self.pushButton_Resume.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Resumes after pause</p></body></html>", None))
        self.pushButton_Features.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Show folder of acquisition (if local).</p></body></html>", None))
        self.pushButton_Skip.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Stop current acquisition and jump to the next.</p></body></html>", None))
        self.pushButton_Stop.setToolTip(_translate("MSiteAcq", "<html><head/><body><p>Stop all the project.</p></body></html>", None))
        self.groupBox_PointsList.setTitle(_translate("MSiteAcq", "Task list", None))
        item = self.tableTasks.horizontalHeaderItem(0)
        item.setText(_translate("MSiteAcq", "To do", None))
        item = self.tableTasks.horizontalHeaderItem(1)
        item.setText(_translate("MSiteAcq", "Sample", None))
        item = self.tableTasks.horizontalHeaderItem(2)
        item.setText(_translate("MSiteAcq", "X", None))
        item = self.tableTasks.horizontalHeaderItem(3)
        item.setText(_translate("MSiteAcq", "Y", None))
        item = self.tableTasks.horizontalHeaderItem(4)
        item.setText(_translate("MSiteAcq", "Z", None))
        item = self.tableTasks.horizontalHeaderItem(5)
        item.setText(_translate("MSiteAcq", "ROI", None))
        item = self.tableTasks.horizontalHeaderItem(6)
        item.setText(_translate("MSiteAcq", "Setup", None))
        item = self.tableTasks.horizontalHeaderItem(7)
        item.setText(_translate("MSiteAcq", "Folder Name", None))
        item = self.tableTasks.horizontalHeaderItem(8)
        item.setText(_translate("MSiteAcq", "Progress", None))
        item = self.tableTasks.horizontalHeaderItem(9)
        item.setText(_translate("MSiteAcq", "CP distance", None))
        __sortingEnabled = self.tableTasks.isSortingEnabled()
        self.tableTasks.setSortingEnabled(False)
        self.tableTasks.setSortingEnabled(__sortingEnabled)
        self.pushButton_save_changes.setText(_translate("MSiteAcq", " Save changes", None))
        self.pushButton_select_all.setText(_translate("MSiteAcq", " Select all", None))
        self.pushButton_deselect_all.setText(_translate("MSiteAcq", " Unselect all", None))
        self.comboBox_StatusTarget.addItems(["--","READY","COMPLETED","CANCELLED"])

        self.groupBox.setTitle(_translate("MSiteAcq", "Sample Running information", None))
        self.label.setText(_translate("MSiteAcq", "Expected Time:", None))
        self.label_Status.setText(_translate("MSiteAcq", "STATUS : STOP", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_list), _translate("MSiteAcq", "Samples list", None))
        self.menu_File.setTitle(_translate("MSiteAcq", "&File", None))
        self.menu_Actions.setTitle(_translate("MSiteAcq", "&Actions", None))
        self.toolBar.setWindowTitle(_translate("MSiteAcq", "toolBar", None))
        self.action_Load_List.setText(_translate("MSiteAcq", "&Load List", None))
        self.actionRun.setText(_translate("MSiteAcq", "&Run", None))
        self.actionStop.setText(_translate("MSiteAcq", "&Stop", None))
        self.action_stop_after_finished.setText(_translate("MSiteAcq", "&Stop after acquisition ends", None))
        self.action_AFASEmergency.setText(_translate("MSiteAcq", "&Execute AFAS", None))
        self.action_SwapCP.setText(_translate("MSiteAcq", "&Swap CP", None))
        self.actionPause.setText(_translate("MSiteAcq", "&Pause", None))
        self.actionResume.setText(_translate("MSiteAcq", "&Resume", None))
        self.action_pushbc.setText(_translate("MSiteAcq", "&Push new B&C ", None))
        self.actionSave_Project.setText(_translate("MSiteAcq", "&Save Project", None))
        self.actionSave_Project.setShortcut(_translate("MSiteAcq", "Ctrl+S", None))
        self.actionLoad_Project.setText(_translate("MSiteAcq", "&Load Project", None))
        self.action_Load_Map.setText(_translate("MSiteAcq", "&Load Map", None))
        self.actionUpdateMap.setText(_translate("MSiteAcq", "&Update Map", None))

