# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JMS\Documents\msite\MSite\msiteSEM\UI\msite2SEM.ui'
#
# Created: Sun Jan 17 19:18:26 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from common.dialogs.mplwidget import *
import common.dialogs.resources_rc


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MSiteSEM(QMainWindow):  # C
    def setupUi(self, MSiteSEM):
        MSiteSEM.setObjectName(_fromUtf8("MSiteSEM"))
        ###############
        MSiteSEM.setWindowModality(QtCore.Qt.NonModal) # C
        screen = QDesktopWidget().screenGeometry()  # C
        MSiteSEM.resize(screen.width(), screen.height()-0.1*screen.height()) # C
        icon_size_32 = int(screen.width() * 32.0 / 1920.0)
        icon_size_48 = int(screen.width()*48.0/1920.0)
        ################
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MSiteSEM.sizePolicy().hasHeightForWidth())
        MSiteSEM.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addPixmap(QPixmap(_fromUtf8(":/res/msite2.png")), QIcon.Normal, QIcon.Off) # C
        MSiteSEM.setWindowIcon(icon)
        MSiteSEM.setStyleSheet(_fromUtf8("border-color: rgb(85, 170, 255);\n"
"color: rgb(0, 28, 132);"))
        MSiteSEM.setDocumentMode(False)
        self.centralwidget = QWidget(MSiteSEM)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        px = int(screen.width()*(20.0/1920))  # C
        py = int(screen.height()*(700.0/1080))
        pxe = int(screen.width()*(822.0/1920))
        pye = int(screen.height()*(120.0/1080))
        self.groupBox_5.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayoutWidget_4 = QWidget(self.groupBox_5)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (401.0 / 1920))
        pye = int(screen.height() * (110.0 / 1080))
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0,0,0,0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_Message = QLabel(self.formLayoutWidget_4)
        self.label_Message.setObjectName(_fromUtf8("label_Message"))
        self.formLayout_4.setWidget(2, QFormLayout.LabelRole, self.label_Message)
        self.label_Error = QLabel(self.formLayoutWidget_4)
        self.label_Error.setObjectName(_fromUtf8("label_Error"))
        self.formLayout_4.setWidget(2, QFormLayout.FieldRole, self.label_Error)
        self.progressBar = QProgressBar(self.formLayoutWidget_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.formLayout_4.setWidget(1, QFormLayout.FieldRole, self.progressBar)
        self.label_2 = QLabel(self.formLayoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_4.setWidget(1, QFormLayout.LabelRole, self.label_2)
        self.label = QLabel(self.groupBox_5)
        px = int(screen.width() * (500.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (150.0 / 1920))
        pye = int(screen.height() * (100.0 / 1080))
        self.label.setGeometry(QtCore.QRect(px, py, pxe, pye))

        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QPixmap(_fromUtf8(":/res/phoebe.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_PointsList = QGroupBox(self.centralwidget)
        px = int(screen.width() * (850.0 / 1920))
        py = int(screen.height() * (160.0 / 1080))
        pxe = int(screen.width() * (900.0 / 1920))
        pye = int(screen.height() * (735.0 / 1080))
        self.groupBox_PointsList.setGeometry(QtCore.QRect(px, py, pxe, pye))
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_PointsList.setFont(font)
        self.groupBox_PointsList.setFlat(False)
        self.groupBox_PointsList.setCheckable(False)
        self.groupBox_PointsList.setObjectName(_fromUtf8("groupBox_PointsList"))
        self.layoutWidget = QWidget(self.groupBox_PointsList)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (721.0 / 1920))
        pye = int(screen.height() * (561.0 / 1080))
        self.layoutWidget.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QTabWidget(self.layoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_lm = QWidget()
        self.tab_lm.setObjectName(_fromUtf8("tab_lm"))
        self.tablePointsLM = QTableWidget(self.tab_lm)
        px = int(screen.width() * (0.0 / 1920))
        py = int(screen.height() * (0.0 / 1080))
        pxe = int(screen.width() * (721.0 / 1920))
        pye = int(screen.height() * (501.0 / 1080))
        self.tablePointsLM.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.tablePointsLM.setStyleSheet(_fromUtf8("background-color: rgb(242, 255, 255);"))
        self.tablePointsLM.setAlternatingRowColors(True)
        self.tablePointsLM.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePointsLM.setCornerButtonEnabled(True)
        self.tablePointsLM.setRowCount(2)
        self.tablePointsLM.setColumnCount(4)
        self.tablePointsLM.setObjectName(_fromUtf8("tablePointsLM"))
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.tablePointsLM.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tablePointsLM.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tablePointsLM.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tablePointsLM.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tablePointsLM.setItem(0, 0, item)
        self.tablePointsLM.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePointsLM.horizontalHeader().setDefaultSectionSize(150)
        self.tabWidget.addTab(self.tab_lm, _fromUtf8(""))
        self.tab_sem = QWidget()
        self.tab_sem.setObjectName(_fromUtf8("tab_sem"))
        self.tablePointsSEM = QTableWidget(self.tab_sem)
        pxe = int(screen.width() * (721.0 / 1920))
        pye = int(screen.height() * (501.0 / 1080))
        self.tablePointsSEM.setGeometry(QtCore.QRect(0, 0, pxe, pye))
        self.tablePointsSEM.setStyleSheet(_fromUtf8("background-color: rgb(242, 255, 255);"))
        self.tablePointsSEM.setAlternatingRowColors(True)
        self.tablePointsSEM.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePointsSEM.setRowCount(2)
        self.tablePointsSEM.setColumnCount(6)
        self.tablePointsSEM.setObjectName(_fromUtf8("tablePointsSEM"))
        item = QTableWidgetItem()
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.tablePointsSEM.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tablePointsSEM.setItem(0, 0, item)
        self.tablePointsSEM.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePointsSEM.horizontalHeader().setDefaultSectionSize(120)
        self.tabWidget.addTab(self.tab_sem, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_Mode = QLabel(self.layoutWidget)
        self.label_Mode.setObjectName(_fromUtf8("label_Mode"))
        self.horizontalLayout_5.addWidget(self.label_Mode)
        self.line = QFrame(self.layoutWidget)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.labelScale = QLabel(self.layoutWidget)
        self.labelScale.setObjectName(_fromUtf8("labelScale"))
        self.horizontalLayout_5.addWidget(self.labelScale)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)

        self.pushButton_Reset = QPushButton(self.layoutWidget)
        self.pushButton_Reset.setObjectName(_fromUtf8("pushButton_Reset"))
        self.horizontalLayout_5.addWidget(self.pushButton_Reset)
        self.pushButton_Delete = QPushButton(self.layoutWidget)
        self.pushButton_Delete.setObjectName(_fromUtf8("pushButton_Delete"))
        self.horizontalLayout_5.addWidget(self.pushButton_Delete)
        self.pushButtonGrid = QPushButton(self.layoutWidget)
        self.pushButtonGrid.setObjectName(_fromUtf8("pushButtonGrid"))
        self.horizontalLayout_5.addWidget(self.pushButtonGrid)
        self.toolButton_Options = QToolButton(self.layoutWidget)
        self.toolButton_Options.setObjectName(_fromUtf8("toolButton_Options"))
        self.horizontalLayout_5.addWidget(self.toolButton_Options)

        self.horizontalLayout_51 = QHBoxLayout()
        self.horizontalLayout_51.setSizeConstraint(QLayout.SetNoConstraint)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_Points = QLabel(self.layoutWidget)
        self.label_Points.setObjectName(_fromUtf8("label_Points"))
        self.comboBox_Points = QComboBox(self.layoutWidget)
        self.comboBox_Points.setObjectName(_fromUtf8("comboBox_Points"))
        self.horizontalLayout_51.addWidget(self.label_Points)
        self.horizontalLayout_51.addWidget(self.comboBox_Points)
        self.horizontalLayout_51.addWidget(self.line)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem)


        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_51)

        self.groupBox_LoadLM = QGroupBox(self.centralwidget)
        px = int(screen.width()*(850.0/1920))
        py = int(screen.height()*(20.0/1080))
        pxe = int(screen.width()*(340.0/1920))
        pye = int(screen.height()*(130.0/1080))
        self.groupBox_LoadLM.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.groupBox_LoadLM.setObjectName(_fromUtf8("groupBox_LoadLM"))
        self.layoutWidget1 = QWidget(self.groupBox_LoadLM)
        px = int(screen.width() * (10.0 / 1920))
        py = int(screen.height() * (30.0 / 1080))
        pxe = int(screen.width() * (246.0 / 1920))
        pye = int(screen.height() * (81.0 / 1080))
        self.layoutWidget1.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0,0,0,0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_Correct = QPushButton(self.layoutWidget1)
        self.pushButton_Correct.setText(_fromUtf8(""))
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(_fromUtf8(":/res/shield.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Correct.setIcon(icon1)
        self.pushButton_Correct.setIconSize(QtCore.QSize(icon_size_48, icon_size_48))
        self.pushButton_Correct.setObjectName(_fromUtf8("pushButton_Correct"))
        self.gridLayout.addWidget(self.pushButton_Correct, 0, 1, 1, 1)
        self.pushButton_Acquire = QPushButton(self.layoutWidget1)
        self.pushButton_Acquire.setText(_fromUtf8(""))
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(_fromUtf8(":/res/flag_orange.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_Acquire.setIcon(icon2)
        self.pushButton_Acquire.setIconSize(QtCore.QSize(icon_size_48, icon_size_48))
        self.pushButton_Acquire.setObjectName(_fromUtf8("pushButton_Acquire"))
        self.gridLayout.addWidget(self.pushButton_Acquire, 0, 3, 1, 1)
        self.pushButton_GiveReference = QPushButton(self.layoutWidget1)
        self.pushButton_GiveReference.setText(_fromUtf8(""))
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(_fromUtf8(":/res/flag_red.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_GiveReference.setIcon(icon3)
        self.pushButton_GiveReference.setIconSize(QtCore.QSize(icon_size_48, icon_size_48))
        self.pushButton_GiveReference.setObjectName(_fromUtf8("pushButton_GiveReference"))
        self.gridLayout.addWidget(self.pushButton_GiveReference, 0, 0, 1, 1)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridView = MplWidgetSEM(self.centralwidget)
        px = int(screen.width()*(20.0/1920))
        py = int(screen.height()*(30.0/1080))
        pxe = int(screen.width()*(821.0/1920))
        pye = int(screen.height()*(681.0/1080))
        self.gridView.setGeometry(QtCore.QRect(px, py, pxe, pye))
        # self.gridView.setMaximumSize(QtCore.QSize(531, 481))
        self.gridView.setAutoFillBackground(False)
        self.gridView.setStyleSheet(_fromUtf8("background-color: black;"))
        self.gridView.setObjectName(_fromUtf8("gridView"))
        self.groupBoxServer = QGroupBox(self.centralwidget)
        px = int(screen.width() * (1230.0 / 1920))
        py = int(screen.height() * (20.0 / 1080))
        pxe = int(screen.width() * (410.0 / 1920))
        pye = int(screen.height() * (130.0 / 1080))
        self.groupBoxServer.setGeometry(QtCore.QRect(px, py, pxe, pye))
        self.groupBoxServer.setObjectName(_fromUtf8("groupBoxServer"))
        self.gridLayout_2 = QGridLayout(self.groupBoxServer)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.hostLineEdit = QLineEdit(self.groupBoxServer)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostLineEdit.sizePolicy().hasHeightForWidth())
        self.hostLineEdit.setSizePolicy(sizePolicy)
        self.hostLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.hostLineEdit.setObjectName(_fromUtf8("hostLineEdit"))
        self.horizontalLayout_2.addWidget(self.hostLineEdit)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.portLineEdit = QLineEdit(self.groupBoxServer)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.portLineEdit.setObjectName(_fromUtf8("portLineEdit"))
        self.horizontalLayout.addWidget(self.portLineEdit)
        spacerItem2 = QSpacerItem(100, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_Connect = QPushButton(self.groupBoxServer)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Connect.setFont(font)
        self.pushButton_Connect.setDefault(False)
        self.pushButton_Connect.setFlat(False)
        self.pushButton_Connect.setObjectName(_fromUtf8("pushButton_Connect"))
        self.horizontalLayout_10.addWidget(self.pushButton_Connect)
        self.pushButton_Refresh = QPushButton(self.groupBoxServer)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Refresh.setFont(font)
        self.pushButton_Refresh.setObjectName(_fromUtf8("pushButton_Refresh"))
        self.horizontalLayout_10.addWidget(self.pushButton_Refresh)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.label_Connect = QLabel(self.groupBoxServer)
        font = QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_Connect.setFont(font)
        self.label_Connect.setObjectName(_fromUtf8("label_Connect"))
        self.horizontalLayout_11.addWidget(self.label_Connect)
        self.label_Led = QLabel(self.groupBoxServer)
        self.label_Led.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Led.setText(_fromUtf8(""))
        self.label_Led.setPixmap(QPixmap(_fromUtf8(":/res/LedNone.ico")))
        self.label_Led.setScaledContents(False)
        self.label_Led.setObjectName(_fromUtf8("label_Led"))
        self.horizontalLayout_11.addWidget(self.label_Led)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        MSiteSEM.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MSiteSEM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Actions = QMenu(self.menubar)
        self.menu_Actions.setObjectName(_fromUtf8("menu_Actions"))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_Plot = QMenu(self.menubar)
        self.menu_Plot.setObjectName(_fromUtf8("menu_Plot"))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MSiteSEM.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MSiteSEM)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MSiteSEM.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MSiteSEM)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(icon_size_32, icon_size_32))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MSiteSEM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QToolBar(MSiteSEM)
        self.toolBar_2.setIconSize(QtCore.QSize(icon_size_32, icon_size_32))
        self.toolBar_2.setFloatable(True)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MSiteSEM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.action_Load_coordinates_Calibration = QAction(MSiteSEM)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(_fromUtf8(":/res/coord_red.png")), QIcon.Normal, QIcon.Off)
        self.action_Load_coordinates_Calibration.setIcon(icon4)
        self.action_Load_coordinates_Calibration.setObjectName(_fromUtf8("action_Load_coordinates_Calibration"))
        self.action_Load_coordinates_Target = QAction(MSiteSEM)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(_fromUtf8(":/res/coord_green.png")), QIcon.Normal, QIcon.Off)
        self.action_Load_coordinates_Target.setIcon(icon5)
        self.action_Load_coordinates_Target.setObjectName(_fromUtf8("action_Load_coordinates_Target"))
        self.action_Save_coordinates_SEM = QAction(MSiteSEM)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(_fromUtf8(":/res/save.ico")), QIcon.Normal, QIcon.Off)
        self.action_Save_coordinates_SEM.setIcon(icon6)
        self.action_Save_coordinates_SEM.setObjectName(_fromUtf8("action_Save_coordinates_SEM"))
        self.action_Save_session = QAction(MSiteSEM)
        self.action_Save_session.setObjectName(_fromUtf8("action_Save_session"))
        self.action_Load_session = QAction(MSiteSEM)
        self.action_Load_session.setObjectName(_fromUtf8("action_Load_session"))
        self.action_Load_coordinates_lm_fromText = QAction(MSiteSEM)
        self.action_Load_coordinates_lm_fromText.setObjectName(_fromUtf8("action_Load_coordinates_lm_fromText"))
        self.action_Load_coordinates_sem_fromText = QAction(MSiteSEM)
        self.action_Load_coordinates_sem_fromText.setObjectName(_fromUtf8("action_Load_coordinates_sem_fromText"))
        self.action_Give_Reference = QAction(MSiteSEM)
        self.action_Give_Reference.setIcon(icon3)
        self.action_Give_Reference.setObjectName(_fromUtf8("action_Give_Reference"))
        self.action_Correct_Position = QAction(MSiteSEM)
        self.action_Correct_Position.setIcon(icon1)
        self.action_Correct_Position.setObjectName(_fromUtf8("action_Correct_Position"))
        self.action_Acquire = QAction(MSiteSEM)
        self.action_Acquire.setIcon(icon2)
        self.action_Acquire.setObjectName(_fromUtf8("action_Acquire"))
        self.action_Plot_Error = QAction(MSiteSEM)
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(_fromUtf8(":/res/chart_line_2.ico")), QIcon.Normal, QIcon.Off)
        self.action_Plot_Error.setIcon(icon7)
        self.action_Plot_Error.setObjectName(_fromUtf8("action_Plot_Error"))

        ##
        self.action_Grab = QAction(MSiteSEM)
        icon71 = QIcon()
        icon71.addPixmap(QPixmap(_fromUtf8(":/res/grab.png")), QIcon.Normal, QIcon.Off)
        self.action_Grab.setIcon(icon71)
        self.action_Grab.setObjectName(_fromUtf8("action_Grab"))

        self.action_correctByRANSAC = QAction(MSiteSEM)
        self.action_correctByRANSAC.setObjectName(_fromUtf8("action_correctByRANSAC"))

        self.action_Stop_Scan = QAction(MSiteSEM)
        icon72 = QIcon()
        icon72.addPixmap(QPixmap(_fromUtf8(":/res/stop.png")), QIcon.Normal, QIcon.Off)
        self.action_Stop_Scan.setIcon(icon72)
        self.action_Stop_Scan.setObjectName(_fromUtf8("action_Stop_Scan"))
        ##
        self.actionSave_coordinates_SEM_as = QAction(MSiteSEM)
        self.actionSave_coordinates_SEM_as.setObjectName(_fromUtf8("actionSave_coordinates_SEM_as"))
        self.actionSave_coordinates_LM_as = QAction(MSiteSEM)
        self.actionSave_coordinates_LM_as.setObjectName(_fromUtf8("actionSave_coordinates_LM_as"))
        self.actionDelete = QAction(MSiteSEM)
        self.actionDelete.setCheckable(True)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(_fromUtf8(":/res/trash.ico")), QIcon.Normal, QIcon.Off)
        self.actionDelete.setIcon(icon8)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.action_Options = QAction(MSiteSEM)
        self.action_Options.setObjectName(_fromUtf8("action_Options"))
        self.actionScan = QAction(MSiteSEM)
        icon9 = QIcon()
        icon9.addPixmap(QPixmap(_fromUtf8(":/res/scanNbuild.png")), QIcon.Normal, QIcon.Off) #C
        self.actionScan.setIcon(icon9)
        self.actionScan.setObjectName(_fromUtf8("actionScan"))
        self.actionCell_Shape_Detection = QAction(MSiteSEM)
        icon10 = QIcon()
        icon10.addPixmap(QPixmap(_fromUtf8(":/res/cell.png")), QIcon.Normal, QIcon.Off)
        self.actionCell_Shape_Detection.setIcon(icon10)
        self.actionCell_Shape_Detection.setObjectName(_fromUtf8("actionCell_Shape_Detection"))
        self.actionNavigate = QAction(MSiteSEM)
        icon11 = QIcon()
        icon11.addPixmap(QPixmap(_fromUtf8(":/res/compass.png")), QIcon.Normal, QIcon.Off)
        self.actionNavigate.setIcon(icon11)
        self.actionNavigate.setObjectName(_fromUtf8("actionNavigate"))
        self.action_Plot_Grid = QAction(MSiteSEM)
        icon12 = QIcon()
        icon12.addPixmap(QPixmap(_fromUtf8(":/res/map_cal.ico")), QIcon.Normal, QIcon.Off)
        self.action_Plot_Grid.setIcon(icon12)
        self.action_Plot_Grid.setObjectName(_fromUtf8("action_Plot_Grid"))

        self.action_Align_Scan = QAction(MSiteSEM)
        self.action_Align_Scan.setObjectName(_fromUtf8("action_Align_Scan"))
        self.action_Quick_Scan = QAction(MSiteSEM)
        self.action_Quick_Scan.setObjectName(_fromUtf8("action_Quick_Scan"))

        self.action_Reset_Calibration = QAction(MSiteSEM)
        self.action_Reset_Calibration.setObjectName(_fromUtf8("action_Reset_Calibration"))

        self.action_AutoCP = QAction(MSiteSEM)
        self.action_AutoCP.setObjectName(_fromUtf8("action_AutoCP"))

        self.action_MakeTrench = QAction(MSiteSEM)
        self.action_MakeTrench.setObjectName(_fromUtf8("action_MakeTrench"))

        self.action_ChangeSettings = QAction(MSiteSEM)
        self.action_ChangeSettings.setObjectName(_fromUtf8("action_ChangeSettings"))

        self.menu_File.addAction(self.action_Load_coordinates_Calibration)
        self.menu_File.addAction(self.action_Load_coordinates_Target)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save_coordinates_SEM)
        self.menu_File.addAction(self.actionSave_coordinates_SEM_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Load_session)
        self.menu_File.addAction(self.action_Save_session)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Load_coordinates_lm_fromText)
        self.menu_File.addAction(self.action_Load_coordinates_sem_fromText)
        self.menu_File.addAction(self.action_ChangeSettings)
        self.menu_Actions.addSeparator()
        self.menu_Actions.addAction(self.action_Give_Reference)
        self.menu_Actions.addAction(self.action_Correct_Position)
        self.menu_Actions.addAction(self.action_Acquire)
        self.menu_Actions.addSeparator()
        self.action_BlockPoint = QAction(MSiteSEM)
        self.action_BlockPoint.setObjectName(_fromUtf8("action_BlockPoint"))
        self.action_UnblockPoint = QAction(MSiteSEM)
        self.action_UnblockPoint.setObjectName(_fromUtf8("action_UnblockPoint"))
        self.action_ConvertToTarget = QAction(MSiteSEM)
        self.action_ConvertToTarget.setObjectName(_fromUtf8("action_ConvertToTarget"))
        self.action_ConvertToCalibrated = QAction(MSiteSEM)
        self.action_ConvertToCalibrated.setObjectName(_fromUtf8("action_ConvertToCalibrated"))
        self.menu_Actions.addAction(self.action_BlockPoint)
        self.menu_Actions.addAction(self.action_UnblockPoint)
        self.menu_Actions.addAction(self.action_ConvertToCalibrated)
        self.menu_Actions.addAction(self.action_ConvertToTarget)
        self.menu_Actions.addAction(self.actionDelete)
        self.menu_Actions.addSeparator()
        self.menu_Actions.addAction(self.actionScan)
        self.menu_Actions.addAction(self.action_Reset_Calibration)
        self.menu_Actions.addAction(self.actionCell_Shape_Detection)
        self.menu_Actions.addAction(self.actionNavigate)
        self.menu_Actions.addAction(self.action_Align_Scan)
        self.menu_Actions.addAction(self.action_Quick_Scan)
        self.menu_Actions.addAction(self.action_correctByRANSAC)
        self.menu_Actions.addAction(self.action_AutoCP)
        self.menu_Actions.addAction(self.action_MakeTrench)
        self.menu_Plot.addAction(self.action_Plot_Error)
        self.menu_Plot.addAction(self.action_Grab)
        self.menu_Plot.addAction(self.action_Plot_Grid)
        self.menuEdit.addAction(self.action_Options)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Actions.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_Plot.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.action_Load_coordinates_Calibration)
        self.toolBar.addAction(self.action_Load_coordinates_Target)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Save_coordinates_SEM)
        self.toolBar_2.addAction(self.action_Give_Reference)
        self.toolBar_2.addAction(self.action_Correct_Position)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.action_Grab)
        self.toolBar_2.addAction(self.actionDelete)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionScan)
        self.toolBar_2.addAction(self.action_Stop_Scan)
        self.toolBar_2.addAction(self.actionCell_Shape_Detection)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionNavigate)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.action_Plot_Grid)
        self.toolBar_2.addAction(self.action_Plot_Error)
        self.toolBar_2.addSeparator()



        self.retranslateUi(MSiteSEM)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MSiteSEM)

    def retranslateUi(self, MSiteSEM):
        MSiteSEM.setWindowTitle(_translate("MSiteSEM", "MSite2 SEM", None))
        self.groupBox_5.setTitle(_translate("MSiteSEM", "Error Measurements", None))
        self.label_Message.setText(_translate("MSiteSEM", "", None))
        self.label_Error.setText(_translate("MSiteSEM", "0.0", None))
        self.label_2.setText(_translate("MSiteSEM", "Scanning :", None))
        self.groupBox_PointsList.setTitle(_translate("MSiteSEM", "Grid Coordinates", None))
        item = self.tablePointsLM.horizontalHeaderItem(0)
        item.setText(_translate("MSiteSEM", "Name", None))
        item = self.tablePointsLM.horizontalHeaderItem(1)
        item.setText(_translate("MSiteSEM", "X", None))
        item = self.tablePointsLM.horizontalHeaderItem(2)
        item.setText(_translate("MSiteSEM", "Y", None))
        item = self.tablePointsLM.horizontalHeaderItem(3)
        item.setText(_translate("MSiteSEM", "Z", None))
        __sortingEnabled = self.tablePointsLM.isSortingEnabled()
        self.tablePointsLM.setSortingEnabled(False)
        self.tablePointsLM.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lm), _translate("MSiteSEM", "LM Coordinates", None))
        item = self.tablePointsSEM.horizontalHeaderItem(0)
        item.setText(_translate("MSiteSEM", "Name", None))
        item = self.tablePointsSEM.horizontalHeaderItem(1)
        item.setText(_translate("MSiteSEM", "X", None))
        item = self.tablePointsSEM.horizontalHeaderItem(2)
        item.setText(_translate("MSiteSEM", "Y", None))
        item = self.tablePointsSEM.horizontalHeaderItem(3)
        item.setText(_translate("MSiteSEM", "Z", None))
        item = self.tablePointsSEM.horizontalHeaderItem(4)
        item.setText(_translate("MSiteSEM", "Error", None))
        item = self.tablePointsSEM.horizontalHeaderItem(5)
        item.setText(_translate("MSiteSEM", "Rp Error", None))
        __sortingEnabled = self.tablePointsSEM.isSortingEnabled()
        self.tablePointsSEM.setSortingEnabled(False)
        self.tablePointsSEM.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sem), _translate("MSiteSEM", "SEM Coordinates", None))
        self.label_Mode.setText(_translate("MSiteSEM", "Mode: OFF", None))
        self.label_Points.setText(_translate("MSiteSEM", "Convert Point Type to:", None))
        self.labelScale.setText(_translate("MSiteSEM", "Scale: not changed", None))
        self.pushButton_Reset.setText(_translate("MSiteSEM", "Reset", None))
        self.pushButton_Delete.setText(_translate("MSiteSEM", "Delete", None))
        self.pushButtonGrid.setText(_translate("MSiteSEM", "Move to", None))
        self.toolButton_Options.setText(_translate("MSiteSEM", "...", None))
        self.groupBox_LoadLM.setTitle(_translate("MSiteSEM", "Actions", None))
        self.gridView.setToolTip(_translate("MSiteSEM", "<html><head/><body><p align=\"justify\">In this grid, you can travel through your sample. </p><p align=\"justify\">Load your points coming from your Light Microscopy, and then go on them with the microscope.</p><p align=\"justify\">Only after you have 5 points, you can move anywhere in the grid just double clicking on it.</p></body></html>", None))
        self.groupBoxServer.setTitle(_translate("MSiteSEM", "SEM Server", None))
        self.hostLineEdit.setToolTip(_translate("MSiteSEM", "<html><head/><body><p>Ip address of SEM Server</p></body></html>", None))
        self.hostLineEdit.setInputMask(_translate("MSiteSEM", "000.000.000.000; ", None))
        self.portLineEdit.setToolTip(_translate("MSiteSEM", "<html><head/><body><p>Port of your server</p></body></html>", None))
        self.portLineEdit.setInputMask(_translate("MSiteSEM", "00000; ", None))
        self.pushButton_Connect.setText(_translate("MSiteSEM", "Connect", None))
        self.pushButton_Refresh.setText(_translate("MSiteSEM", "Save state", None))
        self.label_Connect.setText(_translate("MSiteSEM", "Not connected       ", None))
        self.menu_File.setTitle(_translate("MSiteSEM", "&File", None))
        self.menu_Actions.setTitle(_translate("MSiteSEM", "&Actions", None))
        self.menu.setTitle(_translate("MSiteSEM", "&", None))
        self.menu_Plot.setTitle(_translate("MSiteSEM", "&Plot", None))
        self.menuEdit.setTitle(_translate("MSiteSEM", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MSiteSEM", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MSiteSEM", "toolBar_2", None))
        self.action_Load_coordinates_Calibration.setText(_translate("MSiteSEM", "&Load coordinates Calibration", None))
        self.action_Load_coordinates_Target.setText(_translate("MSiteSEM", "&Load coordinates Target", None))
        self.action_Save_coordinates_SEM.setText(_translate("MSiteSEM", "&Save coordinates SEM", None))
        self.action_Save_coordinates_SEM.setShortcut(_translate("MSiteSEM", "Ctrl+S", None))
        self.action_Save_session.setText(_translate("MSiteSEM", "&Save session", None))
        self.action_Load_session.setText(_translate("MSiteSEM", "&Load session", None))
        self.action_Load_coordinates_lm_fromText.setText(_translate("MSiteSEM", "&Load coordinates LM from text file", None))
        self.action_Load_coordinates_sem_fromText.setText(_translate("MSiteSEM", "&Load coordinates SEM from text file", None))
        self.action_Give_Reference.setText(_translate("MSiteSEM", "&Give Reference", None))
        self.action_Correct_Position.setText(_translate("MSiteSEM", "&Correct Position", None))
        self.action_Acquire.setText(_translate("MSiteSEM", "&Acquire", None))
        self.action_Acquire.setShortcut(_translate("MSiteSEM", "Ctrl+A", None))
        self.action_Plot_Error.setText(_translate("MSiteSEM", "&Plot Error", None))
        self.action_correctByRANSAC.setText(_translate("MSiteSEM", "&Correct by RANSAC", None))
        self.action_AutoCP.setText(_translate("MSiteSEM", "&Automatic coincidence point", None))
        self.action_MakeTrench.setText(_translate("MSiteSEM", "&Make a trench based on recipe", None))
        self.action_ChangeSettings.setText(_translate("MSiteSEM", "&Change settings", None))
        self.actionSave_coordinates_SEM_as.setText(_translate("MSiteSEM", "Save coordinates SEM as ...", None))
        self.action_Grab.setText(_translate("MSiteSEM", "&Grab", None))
        self.action_Grab.setShortcut(_translate("MSiteSEM", "Ctrl+G", None))
        self.actionSave_coordinates_LM_as.setText(_translate("MSiteSEM", "Save coordinates LM as...", None))
        self.actionDelete.setText(_translate("MSiteSEM", "Delete ", None))
        self.actionDelete.setShortcut(_translate("MSiteSEM", "Ctrl+D", None))
        self.action_Reset_Calibration.setText(_translate("MSiteSEM", "&Reset calibrated coordinates.", None))
        self.action_Options.setText(_translate("MSiteSEM", "&Options", None))
        self.actionScan.setText(_translate("MSiteSEM", "&Scan for references and find their SEM positions.", None))
        self.action_Stop_Scan.setText(_translate("MSiteSEM", "&Stop current scanning", None))
        self.actionCell_Shape_Detection.setText(_translate("MSiteSEM", "Show image of cell", None))
        self.actionNavigate.setText(_translate("MSiteSEM", "&Navigate", None))
        self.action_Plot_Grid.setText(_translate("MSiteSEM", "&Plot tiles map", None))
        self.action_Align_Scan.setText(_translate("MSiteSEM", "&Align scan", None))
        self.action_Quick_Scan.setText(_translate("MSiteSEM", "&Load folder with previous scan", None))
        self.action_BlockPoint.setText(_translate("MSiteSEM", "&Block Point", None))
        self.action_UnblockPoint.setText(_translate("MSiteSEM", "&Unblock Point", None))
        self.action_ConvertToCalibrated.setText(_translate("MSiteSEM", "&Convert To Calibrated", None))
        self.action_ConvertToTarget.setText(_translate("MSiteSEM", "&Convert To Target", None))